### ISSUE TITLE
Kubernetes Provider somtimes crash at start up

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1052]
Unclear if this is K8S just refusing because it is unable to register more pods. or something else

```
---> System.Net.Sockets.SocketException (111): Connection refused
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at k8s.Kubernetes.<>c.<<CreateHttpClient>b__1024_0>d.MoveNext()
--- End of stack trace from previous location ---
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
--- End of inner exception stack trace ---
at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
at k8s.WatcherDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
at k8s.Kubernetes.ReadNamespacedPodWithHttpMessagesAsync(String name, String namespaceParameter, String pretty, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at k8s.KubernetesExtensions.ReadNamespacedPodAsync(IKubernetes operations, String name, String namespaceParameter, String pretty, CancellationToken cancellationToken)
at Proto.Cluster.Kubernetes.KubernetesProvider.RegisterMemberAsync()
at Proto.Cluster.Kubernetes.KubernetesProvider.StartMemberAsync(Cluster cluster)
at Proto.Cluster.Cluster.StartMemberAsync()
at KubernetesDiagnostics.Program.Main() in /src/Program.cs:line 79
at KubernetesDiagnostics.Program.<Main>()
```

Relevant bits:
```
at k8s.KubernetesExtensions.ReadNamespacedPodAsync(
at Proto.Cluster.Kubernetes.KubernetesProvider.RegisterMemberAsync()
```

**Comment by rogeralsing** [comment]
Added retries and exponential backoff to the registration.
Will keep an eye on this to see how it works out

**Comment by rogeralsing** [comment]
I'm thinking this is likely a result of an overloaded cluster.
I have only seen this when spawning so many nodes that K8s becomes unresponsive

**Comment by rogeralsing** [comment]
Closing this, have not seen any such issues since retries were introduced.
Can reopen if it reappears
