### ISSUE TITLE
Stabilize Cluster.Identity.MongoDB tests 

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1193]
The Cluster.Identity.MongoDB tests sometimes fail during CI.
Likely due to the build servers being a bit weak, and running tests and an entire database server might be too much.

e.g. I've seen `StoreActivation` method fail due to timeout.
Maybe this is a case where retries would make sense, or simply longer timeouts.

**Comment by rogeralsing** [comment]
```
Stack Trace:
     at MongoDB.Driver.Core.ConnectionPools.ExclusiveConnectionPool.AcquireConnectionAsync(CancellationToken cancellationToken)
....
   at MongoDB.Driver.MongoCollectionBase`1.UpdateOneAsync(FilterDefinition`1 filter, UpdateDefinition`1 update, UpdateOptions options, Func`3 bulkWriteAsync)
   at Proto.Utils.AsyncSemaphore.WaitAsync[T](Func`1 producer) in /home/runner/work/protoactor-dotnet/protoactor-dotnet/src/Proto.Actor/Utils/AsyncSemaphore.cs:line 28

   at Proto.Cluster.Identity.MongoDb.MongoIdentityStorage.StoreActivation(String memberId, SpawnLock spawnLock, PID pid, CancellationToken ct) 
in /home/runner/work/protoactor-dotnet/protoactor-dotnet/src/Proto.Cluster.Identity.MongoDb/MongoIdentityStorage.cs:line 79

```
