### ISSUE TITLE
Problem with ProtoGenTask.

### ISSUE THREAD

**Issue by juliolitwin** [AsynkronIT/protoactor-dotnet#1339]
## Expected Behavior
When the protogen is to be generated, it is having a problem in the final path to save the generated file. He is repeating the project name for some reason. 

Currently the path looks like this: 
`'E:\Projects\ProjectName.IDK\Backend\Project.Actor\Project.Actor\obj\Debug\net6.0\protopotato\Actors-798978F876FA29E2CC0EE50BD029129F.cs'`

And it is expected that it will look like this: 
`'E:\Projects\ProjectName.IDK\Backend\Project.Actor\obj\Debug\net6.0\protopotato\Actors-798978F876FA29E2CC0EE50BD029129F.cs'`

## Actual Behavior
That projects with dot in the name can be used, and the folder repetition problem no longer occurs. 

When using an integer name, if no ".", it works as expected, as can be seen in the RealtimeMap example. 

## Steps to Reproduce the Problem

  1. Create project with name using dots. Example: Project.Actor or Project.API
  2. Try to compile

## Specifications

  - Version: 0.26.1-alpha.0.21
  - Platform: Windows, VS 2022.

## StackTrace
<details>

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "ProtoGenTask" task failed unexpectedly.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Projects\ProjectName.IDK\Backend\Project.Actor\Project.Actor\obj\Debug\net6.0\protopotato\Actors-798978F876FA29E2CC0EE50BD029129F.cs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at Proto.Cluster.CodeGen.Generator.Generate(FileInfo input, FileInfo output, IEnumerable`1 importPath, TaskLoggingHelper log, String rootPath, String template)
   at Proto.Cluster.CodeGen.ProtoGenTask.ProcessFile(String projectDirectory, String objDirectory, String protoFile, String additionalImportDirsString, String templateFilesString)
   at Proto.Cluster.CodeGen.ProtoGenTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Bot.Actor	E:\.nuget\packages\proto.cluster.codegen\0.26.1-alpha.0.21\build\Proto.Cluster.CodeGen.props	17	

```

</details>

**Comment by mhelleborg** [comment]
Thanks @juliolitwin, I'll have a look. Should be quick to find since you found a repro :)

**Comment by juliolitwin** [comment]
Hey @mhelleborg thanks for the feedback!

I saw that you've already done a pull request fixing the bug, unfortunately it failed the test (warning) and it still wasn't possible to update in NuGet. 

This problem has been fixed in the new branch, is there an estimate for you to give PR on this branch or is it still under development?

**Comment by mhelleborg** [comment]
@juliolitwin Merged and built an alpha. Should work now, but I would not take this version to prod yet.  ;-)
