### ISSUE TITLE
Ensure we are not writing mutating messages

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1563]
"GossipResponse System.InvalidOperationException: Did not write as much data as expected."

IIRC , this can be the results of writing when someone else is modifying the message

**Comment by rogeralsing** [comment]
```
Information msg=[ServerConnector][10.240.3.93:8089] Disconnected from 10.240.2.129:8089  tid= sid= 2022-05-09 13:40:49.016 
 tid= sid= 2022-05-09 13:40:49.016 
   at Proto.Remote.Endpoint.RunAsync()
   at Proto.Remote.Endpoint.CreateBatch(IEnumerable`1 m)
   at Proto.Remote.Serialization.Serialize(Object message)
   at Google.Protobuf.MessageExtensions.ToByteString(IMessage message)
   at Google.Protobuf.MessageExtensions.ToByteArray(IMessage message)
Error msg=[10.240.3.93:8089] Error in RunAsync System.InvalidOperationException: Did not write as much data as expected.
````

**Comment by rogeralsing** [comment]
Closing due to inactivity. Reopen if still relevant.
