### ISSUE TITLE
PubSub bug

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#1621]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Proto.Cluster.PubSub.TopicActor.<>c.<OnProducerBatch>b__7_1(ValueTuple`2 subscriber) in /home/runner/work/protoactor-dotnet/protoactor-dotnet/src/Proto.Cluster/PubSub/TopicActor.cs:line 46
   at System.Linq.Lookup`2.Create(IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`2.GetEnumerator()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Proto.Cluster.PubSub.TopicActor.OnProducerBatch(IContext context, PublisherBatchMessage batch) in /home/runner/work/protoactor-dotnet/protoactor-dotnet/src/Proto.Cluster/PubSub/TopicActor.cs:line 48
   at Proto.Context.ActorContext.<InternalInvokeUserMessageAsync>g__Await|[66](https://github.com/asynkron/protoactor-dotnet/runs/6625674245?check_suite_focus=true#step:6:67)_0(ActorContext self, Task t, Boolean resetReceiveTimeout) in /home/runner/work/protoactor-dotnet/protoactor-dotnet/src/Proto.Actor/Context/ActorContext.cs:line 401
```

**Comment by marcinbudny** [comment]
Is this from the test run https://github.com/asynkron/protoactor-dotnet/runs/6625674245?check_suite_focus=true#step:6:65?

Looks like OOM was involved:
![image](https://user-images.githubusercontent.com/2671162/170716982-aefa5b91-fab2-4a90-9916-dec85a1332e9.png)

**Comment by rogeralsing** [comment]
The OOM message above is a false positive, it caught SystemException rather than OutOfMemoryException.

This is what we are seeing now:
<img width="847" alt="Skärmavbild 2022-06-02 kl  15 29 28" src="https://user-images.githubusercontent.com/647031/171640451-ffc31d0e-5ea4-48c8-b238-736c449d95ea.png">

**Comment by marcinbudny** [comment]
What environment is this failing in? I cannot reproduce locally. Can you point me to test results?

**Comment by marcinbudny** [comment]
Issue with tests is resolved now via another PR
