### ISSUE TITLE
[EKS] Timeout in GossipReenterAfterSend

### ISSUE THREAD

**Issue by CloudHolic** [AsynkronIT/protoactor-dotnet#1740]
Expect
---
- Gossip works properly, not throwing an exception

Actual
---
- GossipActor throws TimeoutException

Specifications
---
- Version: 1.0.0-rc2
- Platform: AWS EKS v1.20
- Subsystem: dotnet6
- Node: m5.large
- Limit
```yaml
  resources:
    limits:      
      memory: 2Gi
      cpu: 2000m
    requests:      
      memory: 2Gi
      cpu: 1000m
```
- I found the similar issue on https://github.com/asynkron/protoactor-dotnet/issues/1608. However it just said it's RequestAsync's problem not GossipActor's, with no solution.
- I used default ClusterConfig except ActorRequestTimeout, which is set to 30s.

Log
---
|timestamp|level|message|
|---|---|---|
|16:27.70|Warning|Storing keys in a directory '{path}' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.|
|16:34.95|Error|Receive is taking too long {Elapsed} {Self} incoming message {Message}|
|16:35.00|Info|Starting|
|16:35.00|Info|Starting Proto.Actor server on {Host}:{Port} ({Address})|
|16:35.03|Info|Started Cluster Gossip|
|16:35.03|Info|Starting Gossip Loop|
|16:35.06|Info|[Cluster][KubernetesProvider] Registering service {PodName} on {PodIp}|
|16:35.17|Info|[Cluster][KubernetesProvider] Using Kubernetes namespace: {Namespace}|
|16:35.17|Info|[Cluster][KubernetesProvider] Using Kubernetes port: {Port}|
|16:35.27|Info|Started as cluster member|
|16:35.33|Info|[MemberList] Cluster members joined {MembersJoined}|
|16:35.34|Info|I see myself|
|16:35.34|Info|[MemberList] Cluster members joined {MembersJoined}|
|16:35.34|Info|{SystemId} topology {CurrentTopology} Pausing activations while rebalance in progress, {SpawnCount} spawns waiting|
|16:35.35|Info|{SystemId} topology {CurrentTopology} Pausing activations while rebalance in progress, {SpawnCount} spawns waiting|
|16:35.38|Warning|No XML encryptor configured. Key {KeyId:B} may be persisted to storage in unencrypted form.|
|16:35.41|Info|[ServerConnector][{SystemAddress}] Connecting to {Address}|
|16:35.57|Info|[ServerConnector][{SystemAddress}] Connected to {Address}|
|16:35.68|Info|[EndpointReader][{SystemAddress}] Accepted connection request from {Remote} to {Local}|
|16:35.74|Info|[PartitionIdentity] Pulling activations for topology {CurrentTopology} from {@MemberAddresses}|
|16:35.75|Info|[PartitionIdentity] Pulled activations from {MemberCount} partitions completed in {Elapsed}|
|16:35.75|Info|[PartitionIdentity] Topology {TopologyHash} rebalance completed in {Elapsed}, received {@Stats}|
|16:36.90|Error|Actor {Self} {ActorType} Got exception waiting for RequestAsync response of {MessageType}:{Message} from {Target}|
|16:36.90|Warning|Timeout in GossipReenterAfterSend|
|16:37.19|Error|Actor {Self} {ActorType} Got exception waiting for RequestAsync response of {MessageType}:{Message} from {Target}|
|16:37.19|Warning|Timeout in GossipReenterAfterSend|
|16:37.49|Error|Actor {Self} {ActorType} Got exception waiting for RequestAsync response of {MessageType}:{Message} from {Target}|
|16:37.49|Warning|Timeout in GossipReenterAfterSend|
|16:37.80|Error|Actor {Self} {ActorType} Got exception waiting for RequestAsync response of {MessageType}:{Message} from {Target}|
|16:37.80|Warning|Timeout in GossipReenterAfterSend|
|...|...|...|

- After that, the RequestAsync error and Timeout warning messages appear rotationally.
- The RequestAsync error message looks like this:
```
Level | Error
MessageTemplate | Actor {Self} {ActorType} Got exception waiting for RequestAsync response of {MessageType}:{Message} from {Target}
--
System.TimeoutException: Request didn't receive any Response within the expected time.
at Proto.Future.SharedFutureProcess.SharedFutureHandle.GetTask(CancellationToken cancellationToken)
at Proto.SenderContextExtensions.RequestAsync[T](ISenderContext self, PID target, Object message, CancellationToken cancellationToken)
at Proto.ActorLoggingContext.RequestAsync[T](PID target, Object message, CancellationToken cancellationToken)
```
- It seems that a long job at 16:34.95 blocked a thread, and the gossip loop was affected by this block.
  - This long job takes slightly more than 5 secs (5.8070149, exactly).
  - It's just my guess, it might not be true.

**Comment by rogeralsing** [comment]
At the moment I do not have any good answer for this.
There is nothing blocking inside the Gossip actor itself.

Could it be that the nodes you are running have very few cores? e.g. 2 cores?

Can you reproduce it even if you explicitly set MinThreads to some highish number, e.g 50 threads or something?
https://learn.microsoft.com/en-us/dotnet/api/system.threading.threadpool.setminthreads?view=net-6.0

We have seen that gossip can time out if there is CPU throttling in Kubernetes. e.g. a quick spike of CPU load. which then throttles. and this is not visible in various dashboards, just because they aggregate the data.

Coming up with a proper reproduction scenario would be great to further investigate

**Comment by rogeralsing** [comment]
Closing due to inactivity. Reopen if still relevant.
