### ISSUE TITLE
Cluster monitor bug

### ISSUE THREAD

**Issue by jrouaix** [AsynkronIT/protoactor-dotnet#284]
Found a potential bug (@rogeralsing saying so, perhaps related to the new Serializer support) in the cluster monitoring system ... somehow doesn't work anymore.

**FROM GITTER CHAT**

Hello guys, i'm playing with the the cluster capabilities of protoC# with ClusterGrainHelloWorld example.
- If launch node1 & node2 (node2 is the grain host, node1 is the "client")
- When I'm creating many clients with different graind ids on node client => those grains are created on the node2 => Perfect!
- If I launch a second instance of the node2 (using a different port of course) => the new node in consul => bug all new grains created from now are created on the first node2, none are created on the one I just launched => should be some balancing at this point ?
- Then I kill the first node2, and my client node1 hang on creating any more more grain client => shouldn't it take the hit and balance to the new one ?

Ok, I have a balancing if I start many node2 before the client node. So I undestand a dynamic cluster is not yet implemented ?

**Comment by jrouaix** [comment]
When introducing a second node2, I get an exception in the task instanciated in MonitorMemberStatusChanges (by the way this method can crash without anyone will ever know about)

**The given key was not present in the dictionary.**

   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Proto.Cluster.Consul.ConsulProvider.<>c__DisplayClass17_0.<NotifyStatusesAsync>b__1(<>f__AnonymousType0`2 <>h__TransparentIdentifier0) in D:\_git\protoactor-dotnet-origin\src\ClusterProviders\Proto.Cluster.Consul\ConsulProvider.cs:line 170
   at System.Linq.Enumerable.<>c__DisplayClass151_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass151_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.<>c__DisplayClass151_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Proto.Cluster.ClusterTopologyEvent..ctor(IEnumerable`1 statuses) in D:\_git\protoactor-dotnet-origin\src\Proto.Cluster\MemberStatusEvents.cs:line 36
   at Proto.Cluster.Consul.ConsulProvider.<NotifyStatusesAsync>d__17.MoveNext() in D:\_git\protoactor-dotnet-origin\src\ClusterProviders\Proto.Cluster.Consul\ConsulProvider.cs:line 173
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Proto.Cluster.Consul.ConsulProvider.<<MonitorMemberStatusChanges>b__14_0>d.MoveNext() in D:\_git\protoactor-dotnet-origin\src\ClusterProviders\Proto.Cluster.Consul\ConsulProvider.cs:line 120

**Comment by jrouaix** [comment]
There was at least a bug in NotifyStatusesAsync. I made a PR : https://github.com/AsynkronIT/protoactor-dotnet/pull/285

Not sure yet it's all over, just a node now can stand another one comes on the dancefloor.

**Comment by rogeralsing** [comment]
Any feedback on this, is this still an issue?

**Comment by rogeralsing** [comment]
Closing this as Cluster has had some major upgrades
