### ISSUE TITLE
graceful exceptions in proto.remote

### ISSUE THREAD

**Issue by rogeralsing** [AsynkronIT/protoactor-dotnet#790]
Let it crash is cool and all. but maybe we should really try to do a bit more graceful error handling of lost connections

```
         at Grpc.Net.Client.Internal.GrpcCall`2.RunCall(HttpRequestMessage request, Nullable`1 timeout)")
         at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)
         at Proto.Remote.EndpointActor.<>c__DisplayClass16_0.<<ConnectAsync>b__0>d.MoveNext() in /Users/rogerjohansson/git/asynkron/protoactor-dotnet/src/Proto.Remote/Endpoints/EndpointActor.cs:line 92
fail: Grpc.AspNetCore.Server.ServerCallHandler[6]
      Error when executing service method 'Receive'.
      System.IO.IOException: The request stream was aborted.
       ---> Microsoft.AspNetCore.Connections.ConnectionAbortedException: The HTTP/2 connection faulted.
```

we could easily catch that and notify this cleaner to the system.
long stacktraces in perfectly normal conditions are just scary.

**Comment by rogeralsing** [comment]
done
